### ISSUE TITLE
Got 500 error when Tracking WordPress feed request

### ISSUE THREAD

**Issue by wuzhongyi1105** [Open-Web-Analytics/owa-wordpress-plugin#3]
Wordpress debug log says:
```
[11-Jan-2022 13:52:16 UTC] Tracking WordPress feed request
[11-Jan-2022 13:52:16 UTC] PHP Fatal error:  Uncaught Error: Call to private method OwaSdk\Tracker\TrackerClient::makeEvent() from context 'owaWp_plugin' in /var/www/vhosts/example.com/blog.example.com/wp-content/plugins/open-web-analytics/owa-plugin.php:919
Stack trace:
#0 /var/www/vhosts/example.com/blog.example.com/wp-includes/class-wp-hook.php(303): owaWp_plugin->trackFeedRequest()
#1 /var/www/vhosts/example.com/blog.example.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /var/www/vhosts/example.com/blog.example.com/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /var/www/vhosts/example.com/blog.example.com/wp-includes/template-loader.php(13): do_action()
#4 /var/www/vhosts/example.com/blog.example.com/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#5 /var/www/vhosts/example.com/blog.example.com/index.php(17): require('/var/www/vhosts...')
#6 {main}
  thrown in /var/www/vhosts/example.com/blog.example.com/wp-content/plugins/open-web-analytics/owa-plugin.php on line 919
```

**Comment by mehdiMj-ir** [comment]
what is your `PHP`, `OS`, `Web Server`, `Database` and `WP` version?

are we have a same problem #2 ?
