### ISSUE TITLE
Uncaught Error: Interface 'Psr\Http\Message\RequestInterface' not found in /home/customer/...

### ISSUE THREAD

**Issue by hneal98** [Open-Web-Analytics/owa-wordpress-plugin#6]
I searched this site but wasn't sure what I was searching for.  The error is not very clear as to what the issue is.  It seems there is something missing, but when you look further down, it appears there is an error on line 15 of the owa_coreAPI.php.  Let me know if, perhaps, I just missed something.

Fatal error: Uncaught Error: Interface 'Psr\Http\Message\RequestInterface' not found in /home/customer/www/gardening-diy.com/public_html/OWA/vendor/guzzlehttp/psr7/src/Request.php:15 Stack trace: #0 /home/customer/www/gardening-diy.com/public_html/OWA/vendor/composer/ClassLoader.php(571): include() #1 /home/customer/www/gardening-diy.com/public_html/OWA/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/customer/...') #2 [internal function]: Composer\Autoload\ClassLoader->loadClass('GuzzleHttp\\Psr7...') #3 /home/customer/www/gardening-diy.com/public_html/OWA/owa_httpRequest.php(179): spl_autoload_call('GuzzleHttp\\Psr7...') #4 /home/customer/www/gardening-diy.com/public_html/OWA/modules/base/widgetOwaNews.php(49): owa_http->getRequest('https://api.git...') #5 /home/customer/www/gardening-diy.com/public_html/OWA/owa_controller.php(280): owa_widgetOwaNewsController->action() #6 /home/customer/www/gardening-diy.com/public_html/OWA/owa_coreAPI.php(880): owa_controller->doAction() #7 /home/customer/www in /home/customer/www/gardening-diy.com/public_html/OWA/vendor/guzzlehttp/psr7/src/Request.php on line 15

**Comment by padams** [comment]
What version of PHP are you running?
