### ISSUE TITLE
Unable to configure Website ID in plugin

### ISSUE THREAD

**Issue by psychedelicatessen** [Open-Web-Analytics/owa-wordpress-plugin#7]
**Description**  
I just successfully installed the OWA server. Everything seems to be working fine. The installation wizard completed successfully and I am able to navigate to the URL and log into the OWA instance.

While trying to connect the OWA server with my wordpress website, the plugin will not populate the drop down menu with the website ID. I am not sure why this is. I have went through the trouble shooting guide in the OWA wiki and none of the suggestions have been helpful for this issue.

I am running both the OWA server and the website over nginx on RockyLinux.

Below are a few lines from the error logs which may be helpful.

[NOTICE] Use of owa_client class is deprecated. Re-implement your tracker using OWA's PHP SDK. 
[ERROR] OWA_DB_TYPE constant has not been set for some reason. 

These errors are present immediately after installation.

I did try to install the PHP SDK, but I was unclear on how to properly pass the credentials to it. I did not understand the directions for creating a tracker.

Thank you for any assistance you can provide.

Edit: While continuing to try to fix the issue. I set the plugin option "Enable OWA" to "Off". This resulted in the error "There has been a critical error on this website. Please check your site admin email inbox for instructions."

This error persists even after reinstalling the plugin. There are no clear indications about what is wrong or how to fix it.

Here are the errors which were pushed to my email in regards to the plugin:

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.1.1
Active theme: GeneratePress Child (version 0.1)
Current plugin: Open Web Analytics (version 2.1.5)
PHP version 7.4.30

Error Details
=============
An error of type E_ERROR was caused in line 1190 of the file /var/www/***.com/html/wp-content/plugins/open-web-analytics/owa-plugin.php. Error message: Uncaught Error: Call to a member function createSites() on string in /var/www/***.com/html/wp-content/plugins/open-web-analytics/owa-plugin.php:1190
Stack trace:
#0 /var/www/***.com/html/wp-includes/class-wp-hook.php(308): owaWp_plugin->getSitesFromOwa()
#1 /var/www/***.com/html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /var/www/***.com/html/wp-content/plugins/open-web-analytics/src/settings/fields/select.php(19): apply_filters()
#3 /var/www/***.com/html/wp-admin/includes/template.php(1785): owaWp\settings\fields\select->render()
#4 /var/www/***.com/html/wp-content/plugins/open-web-analytics/src/settings/page.php(428): do_settings_fields()
#5 /var/www/***.com/html/wp-content/plugins/open-web-analytics/src/settings/page.php(289): owaWp\settings\page->doTabbedSettingsSections()
#6 /var/www/***.com/html/wp-includes/class-wp-hook.php(308): owaWp\settings\page->renderPage()
#7 /var/www/***.com/html/wp-includes/class-wp-hook.php(332): WP_

(censored my FQDN for privacy reasons)

**Comment by iYoungblood** [comment]
I also have this issue. 

<html>
<body>


if ( $this->isOwaSdkready() ) {
--
1189 |  
1190 | $sites_client = $this->owaSdk->createSites();
1191 | $sites = $sites_client->listSites();
1192 | }


</body>
</html>


Errors out of line 1190 - createSites() 

I do not see a funcation createSites anywhere and also cannot find listSites()
